name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  # 배포할 브랜치명
  workflow_dispatch:  # 수동 실행도 가능

env:
  AZURE_CONTAINER_APP_NAME: "squat-api"
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/squat-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Container Registry 로그인
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      # 태그 2개(latest, commit-sha)
      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .  # Dockerfile이 있는 위치
          push: true  # 빌드 후 푸시
          tags: |
            ${{ env.IMAGE_PATH }}:latest
            ${{ env.IMAGE_PATH }}:${{ github.sha }}

      # Azure 로그인
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure Container Apps에 배포
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ env.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ env.IMAGE_PATH }}:${{ github.sha }}
          registryServer: ghcr.io

